/**
 * Demo pages for gallery - Business tier examples
 * 2 demo pages per each of 15 niches = 30 total
 */

import type { GalleryPage } from '@/services/gallery';
import type { Niche } from '@/lib/niches';

export interface DemoPage extends GalleryPage {
  isDemo: true;
  tier: 'business';
  blocks: DemoBlock[];
}

export interface DemoBlock {
  type: string;
  content: Record<string, unknown>;
}

// Demo pages data
export const DEMO_PAGES: DemoPage[] = [
  // ========== BEAUTY (2 pages) ==========
  {
    id: 'demo-beauty-1',
    slug: 'demo-anna-nails',
    title: 'Анна | Nail Artist',
    description: 'Маникюр и педикюр в Алматы. Запись онлайн 24/7. Премиум материалы, уютная студия.',
    avatar_url: 'https://images.unsplash.com/photo-1594744803329-e58b31de8bf5?w=200&h=200&fit=crop&crop=face',
    preview_url: 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=800&h=600&fit=crop',
    gallery_likes: 847,
    view_count: 12450,
    is_premium: true,
    niche: 'beauty' as Niche,
    gallery_featured_at: new Date().toISOString(),
    isDemo: true,
    tier: 'business',
    blocks: [
      { type: 'profile', content: { name: 'Анна', title: 'Nail Artist', bio: 'Создаю красоту на ваших ноготках уже 7 лет ✨' } },
      { type: 'booking', content: { title: 'Записаться на маникюр' } },
      { type: 'catalog', content: { title: 'Мои работы', items: 12 } },
      { type: 'pricing', content: { title: 'Прайс-лист' } },
      { type: 'testimonial', content: { count: 48 } },
      { type: 'messenger', content: { whatsapp: true, telegram: true } },
      { type: 'map', content: { address: 'Алматы, ул. Абая 150' } },
    ],
  },
  {
    id: 'demo-beauty-2',
    slug: 'demo-salon-luxe',
    title: 'Luxe Beauty Studio',
    description: 'Салон красоты полного цикла. Волосы, ногти, брови, макияж. Команда из 8 мастеров.',
    avatar_url: 'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=200&h=200&fit=crop',
    preview_url: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&h=600&fit=crop',
    gallery_likes: 1203,
    view_count: 18900,
    is_premium: true,
    niche: 'beauty' as Niche,
    gallery_featured_at: new Date().toISOString(),
    isDemo: true,
    tier: 'business',
    blocks: [
      { type: 'profile', content: { name: 'Luxe Beauty Studio', bio: 'Премиум салон в центре города' } },
      { type: 'carousel', content: { images: 6 } },
      { type: 'booking', content: { title: 'Онлайн-запись' } },
      { type: 'catalog', content: { title: 'Услуги', categories: ['Волосы', 'Ногти', 'Брови', 'Макияж'] } },
      { type: 'community', content: { team: 8 } },
      { type: 'faq', content: { questions: 5 } },
      { type: 'socials', content: { instagram: true, tiktok: true } },
    ],
  },

  // ========== FITNESS (2 pages) ==========
  {
    id: 'demo-fitness-1',
    slug: 'demo-coach-max',
    title: 'Максим | Фитнес-тренер',
    description: 'Персональные тренировки онлайн и офлайн. Трансформация тела за 12 недель.',
    avatar_url: 'https://images.unsplash.com/photo-1567013127542-490d757e51fc?w=200&h=200&fit=crop&crop=face',
    preview_url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800&h=600&fit=crop',
    gallery_likes: 634,
    view_count: 9870,
    is_premium: true,
    niche: 'fitness' as Niche,
    gallery_featured_at: new Date().toISOString(),
    isDemo: true,
    tier: 'business',
    blocks: [
      { type: 'profile', content: { name: 'Максим Петров', title: 'Фитнес-тренер', bio: 'Сертифицированный тренер. 500+ клиентов.' } },
      { type: 'before-after', content: { results: 12 } },
      { type: 'product', content: { title: 'Программа трансформации 12 недель', price: 89000 } },
      { type: 'booking', content: { title: 'Записаться на консультацию' } },
      { type: 'video', content: { title: 'Мои тренировки' } },
      { type: 'testimonial', content: { count: 67 } },
      { type: 'messenger', content: { telegram: true, whatsapp: true } },
    ],
  },
  {
    id: 'demo-fitness-2',
    slug: 'demo-yoga-studio',
    title: 'Yoga Flow Studio',
    description: 'Йога для всех уровней. Групповые и индивидуальные занятия. Онлайн-курсы.',
    avatar_url: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=200&h=200&fit=crop',
    preview_url: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=800&h=600&fit=crop',
    gallery_likes: 892,
    view_count: 14320,
    is_premium: true,
    niche: 'fitness' as Niche,
    gallery_featured_at: new Date().toISOString(),
    isDemo: true,
    tier: 'business',
    blocks: [
      { type: 'profile', content: { name: 'Yoga Flow Studio', bio: 'Найди гармонию тела и духа 🧘‍♀️' } },
      { type: 'carousel', content: { images: 8 } },
      { type: 'pricing', content: { title: 'Абонементы' } },
      { type: 'booking', content: { title: 'Расписание занятий' } },
      { type: 'product', content: { title: 'Онлайн-курс для начинающих', price: 15000 } },
      { type: 'community', content: { instructors: 4 } },
      { type: 'map', content: { address: 'Нур-Султан, ул. Кабанбай батыра 62' } },
    ],
  },

  // ========== FOOD (2 pages) ==========
  {
    id: 'demo-food-1',
    slug: 'demo-chef-elena',
    title: 'Елена | Домашняя кухня',
    description: 'Домашние торты и десерты на заказ. Натуральные ингредиенты, авторские рецепты.',
    avatar_url: 'https://images.unsplash.com/photo-1556911220-bff31c812dba?w=200&h=200&fit=crop&crop=face',
    preview_url: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&h=600&fit=crop',
    gallery_likes: 1456,
    view_count: 21300,
    is_premium: true,
    niche: 'food' as Niche,
    gallery_featured_at: new Date().toISOString(),
    isDemo: true,
    tier: 'business',
    blocks: [
      { type: 'profile', content: { name: 'Елена', title: 'Кондитер', bio: 'Пеку с любовью для ваших праздников 🎂' } },
      { type: 'catalog', content: { title: 'Каталог тортов', items: 24 } },
      { type: 'pricing', content: { title: 'Прайс' } },
      { type: 'form', content: { title: 'Оставить заявку' } },
      { type: 'carousel', content: { images: 12 } },
      { type: 'testimonial', content: { count: 89 } },
      { type: 'messenger', content: { whatsapp: true, instagram: true } },
    ],
  },
  {
    id: 'demo-food-2',
    slug: 'demo-healthy-food',
    title: 'GreenBox | Здоровое питание',
    description: 'Доставка здорового питания. Рационы на неделю. КБЖУ рассчитано.',
    avatar_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=200&h=200&fit=crop',
    preview_url: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&h=600&fit=crop',
    gallery_likes: 723,
    view_count: 11200,
    is_premium: true,
    niche: 'food' as Niche,
    gallery_featured_at: new Date().toISOString(),
    isDemo: true,
    tier: 'business',
    blocks: [
      { type: 'profile', content: { name: 'GreenBox', bio: 'Вкусно. Полезно. С доставкой.' } },
      { type: 'catalog', content: { title: 'Меню на неделю' } },
      { type: 'pricing', content: { title: 'Тарифы', plans: ['Lite', 'Standard', 'Premium'] } },
      { type: 'countdown', content: { title: 'Скидка 20% до конца недели' } },
      { type: 'form', content: { title: 'Заказать рацион' } },
      { type: 'faq', content: { questions: 6 } },
      { type: 'messenger', content: { telegram: true } },
    ],
  },

  // ========== EDUCATION (2 pages) ==========
  {
    id: 'demo-education-1',
    slug: 'demo-english-teacher',
    title: 'Мария | Английский язык',
    description: 'Репетитор английского. Подготовка к IELTS, разговорный, бизнес-английский.',
    avatar_url: 'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?w=200&h=200&fit=crop&crop=face',
    preview_url: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&h=600&fit=crop',
    gallery_likes: 567,
    view_count: 8900,
    is_premium: true,
    niche: 'education' as Niche,
    gallery_featured_at: new Date().toISOString(),
    isDemo: true,
    tier: 'business',
    blocks: [
      { type: 'profile', content: { name: 'Мария Иванова', title: 'Преподаватель английского', bio: 'IELTS 8.5. Опыт преподавания 10 лет.' } },
      { type: 'pricing', content: { title: 'Форматы занятий' } },
      { type: 'booking', content: { title: 'Записаться на пробный урок' } },
      { type: 'product', content: { title: 'Интенсив IELTS 30 дней', price: 120000 } },
      { type: 'testimonial', content: { count: 34 } },
      { type: 'video', content: { title: 'Отзывы учеников' } },
      { type: 'messenger', content: { telegram: true, whatsapp: true } },
    ],
  },
  {
    id: 'demo-education-2',
    slug: 'demo-coding-school',
    title: 'CodeKids | Программирование',
    description: 'Курсы программирования для детей 7-16 лет. Python, Scratch, веб-разработка.',
    avatar_url: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=200&h=200&fit=crop',
    preview_url: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=800&h=600&fit=crop',
    gallery_likes: 445,
    view_count: 7600,
    is_premium: true,
    niche: 'education' as Niche,
    gallery_featured_at: new Date().toISOString(),
    isDemo: true,
    tier: 'business',
    blocks: [
      { type: 'profile', content: { name: 'CodeKids', bio: 'Учим детей создавать будущее 💻' } },
      { type: 'catalog', content: { title: 'Наши курсы', categories: ['Python', 'Scratch', 'Web', 'Робототехника'] } },
      { type: 'pricing', content: { title: 'Стоимость обучения' } },
      { type: 'form', content: { title: 'Записаться на пробное занятие' } },
      { type: 'community', content: { teachers: 6 } },
      { type: 'carousel', content: { images: 8 } },
      { type: 'faq', content: { questions: 8 } },
    ],
  },

  // ========== ART (2 pages) ==========
  {
    id: 'demo-art-1',
    slug: 'demo-artist-dmitry',
    title: 'Дмитрий | Художник',
    description: 'Портреты на заказ. Масло, акварель, цифровое искусство. Доставка по СНГ.',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face',
    preview_url: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=800&h=600&fit=crop',
    gallery_likes: 892,
    view_count: 13400,
    is_premium: true,
    niche: 'art' as Niche,
    gallery_featured_at: new Date().toISOString(),
    isDemo: true,
    tier: 'business',
    blocks: [
      { type: 'profile', content: { name: 'Дмитрий Козлов', title: 'Художник', bio: 'Превращаю эмоции в искусство 🎨' } },
      { type: 'catalog', content: { title: 'Галерея работ', items: 36 } },
      { type: 'pricing', content: { title: 'Стоимость портретов' } },
      { type: 'form', content: { title: 'Заказать портрет' } },
      { type: 'before-after', content: { title: 'Процесс создания' } },
      { type: 'testimonial', content: { count: 28 } },
      { type: 'messenger', content: { telegram: true, instagram: true } },
    ],
  },
  {
    id: 'demo-art-2',
    slug: 'demo-photo-studio',
    title: 'Moments | Фотостудия',
    description: 'Профессиональная фотосъемка. Свадьбы, портреты, предметка. Аренда студии.',
    avatar_url: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=200&h=200&fit=crop',
    preview_url: 'https://images.unsplash.com/photo-1554080353-a576cf803bda?w=800&h=600&fit=crop',
    gallery_likes: 1123,
    view_count: 16700,
    is_premium: true,
    niche: 'art' as Niche,
    gallery_featured_at: new Date().toISOString(),
    isDemo: true,
    tier: 'business',
    blocks: [
      { type: 'profile', content: { name: 'Moments Studio', bio: 'Сохраняем ваши лучшие моменты 📸' } },
      { type: 'carousel', content: { images: 16 } },
      { type: 'catalog', content: { title: 'Услуги', categories: ['Свадьбы', 'Портреты', 'Предметка', 'Аренда'] } },
      { type: 'pricing', content: { title: 'Пакеты съемок' } },
      { type: 'booking', content: { title: 'Забронировать дату' } },
      { type: 'community', content: { photographers: 3 } },
      { type: 'map', content: { address: 'Алматы, ул. Желтоксан 87' } },
    ],
  },

  // ========== MUSIC (2 pages) ==========
  {
    id: 'demo-music-1',
    slug: 'demo-dj-alex',
    title: 'DJ Alex | Музыкант',
    description: 'DJ на свадьбы, корпоративы, частные вечеринки. 10 лет опыта.',
    avatar_url: 'https://images.unsplash.com/photo-1571266028243-3716f02d3f85?w=200&h=200&fit=crop&crop=face',
    preview_url: 'https://images.unsplash.com/photo-1571266028243-3716f02d3f85?w=800&h=600&fit=crop',
    gallery_likes: 534,
    view_count: 8200,
    is_premium: true,
    niche: 'music' as Niche,
    gallery_featured_at: new Date().toISOString(),
    isDemo: true,
    tier: 'business',
    blocks: [
      { type: 'profile', content: { name: 'DJ Alex', title: 'Диджей', bio: 'Создаю атмосферу вашего праздника 🎧' } },
      { type: 'video', content: { title: 'Мои сеты' } },
      { type: 'pricing', content: { title: 'Стоимость выступления' } },
      { type: 'booking', content: { title: 'Забронировать дату' } },
      { type: 'carousel', content: { images: 10 } },
      { type: 'testimonial', content: { count: 42 } },
      { type: 'socials', content: { instagram: true, soundcloud: true } },
    ],
  },
  {
    id: 'demo-music-2',
    slug: 'demo-vocal-school',
    title: 'VoiceLab | Школа вокала',
    description: 'Уроки вокала для взрослых и детей. Эстрада, джаз, рок. Подготовка к конкурсам.',
    avatar_url: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=200&h=200&fit=crop',
    preview_url: 'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=800&h=600&fit=crop',
    gallery_likes: 378,
    view_count: 6100,
    is_premium: true,
    niche: 'music' as Niche,
    gallery_featured_at: new Date().toISOString(),
    isDemo: true,
    tier: 'business',
    blocks: [
      { type: 'profile', content: { name: 'VoiceLab', bio: 'Раскрой свой голос 🎤' } },
      { type: 'video', content: { title: 'Выступления учеников' } },
      { type: 'pricing', content: { title: 'Абонементы' } },
      { type: 'booking', content: { title: 'Записаться на пробный урок' } },
      { type: 'community', content: { teachers: 4 } },
      { type: 'testimonial', content: { count: 23 } },
      { type: 'faq', content: { questions: 5 } },
    ],
  },

  // ========== TECH (2 pages) ==========
  {
    id: 'demo-tech-1',
    slug: 'demo-web-developer',
    title: 'Артем | Веб-разработчик',
    description: 'Создание сайтов и веб-приложений. React, Node.js. Фриланс, удаленно.',
    avatar_url: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=200&h=200&fit=crop&crop=face',
    preview_url: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800&h=600&fit=crop',
    gallery_likes: 456,
    view_count: 7300,
    is_premium: true,
    niche: 'tech' as Niche,
    gallery_featured_at: new Date().toISOString(),
    isDemo: true,
    tier: 'business',
    blocks: [
      { type: 'profile', content: { name: 'Артем Волков', title: 'Веб-разработчик', bio: 'Создаю сайты, которые работают на вас 💻' } },
      { type: 'catalog', content: { title: 'Портфолио', items: 18 } },
      { type: 'pricing', content: { title: 'Услуги и цены' } },
      { type: 'form', content: { title: 'Оставить заявку' } },
      { type: 'testimonial', content: { count: 31 } },
      { type: 'download', content: { title: 'Презентация услуг' } },
      { type: 'messenger', content: { telegram: true } },
    ],
  },
  {
    id: 'demo-tech-2',
    slug: 'demo-smm-agency',
    title: 'DigiBoost | SMM агентство',
    description: 'Продвижение в соцсетях. Таргет, контент, Reels. Работаем с бизнесом СНГ.',
    avatar_url: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=200&h=200&fit=crop',
    preview_url: 'https://images.unsplash.com/photo-1432888622747-4eb9a8f5a70a?w=800&h=600&fit=crop',
    gallery_likes: 678,
    view_count: 10500,
    is_premium: true,
    niche: 'tech' as Niche,
    gallery_featured_at: new Date().toISOString(),
    isDemo: true,
    tier: 'business',
    blocks: [
      { type: 'profile', content: { name: 'DigiBoost', bio: 'Приводим клиентов из соцсетей 🚀' } },
      { type: 'before-after', content: { title: 'Кейсы роста' } },
      { type: 'pricing', content: { title: 'Тарифы', plans: ['Start', 'Growth', 'Scale'] } },
      { type: 'form', content: { title: 'Бесплатный аудит' } },
      { type: 'community', content: { team: 5 } },
      { type: 'testimonial', content: { count: 47 } },
      { type: 'socials', content: { instagram: true, telegram: true } },
    ],
  },

  // ========== BUSINESS (2 pages) ==========
  {
    id: 'demo-business-1',
    slug: 'demo-business-coach',
    title: 'Алексей | Бизнес-коуч',
    description: 'Стратегические сессии для предпринимателей. Рост x3 за 6 месяцев.',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&crop=face',
    preview_url: 'https://images.unsplash.com/photo-1553028826-f4804a6dba3b?w=800&h=600&fit=crop',
    gallery_likes: 923,
    view_count: 14200,
    is_premium: true,
    niche: 'business' as Niche,
    gallery_featured_at: new Date().toISOString(),
    isDemo: true,
    tier: 'business',
    blocks: [
      { type: 'profile', content: { name: 'Алексей Громов', title: 'Бизнес-коуч', bio: '15 лет в бизнесе. 200+ клиентов.' } },
      { type: 'before-after', content: { title: 'Результаты клиентов' } },
      { type: 'product', content: { title: 'Стратегическая сессия 2 часа', price: 150000 } },
      { type: 'booking', content: { title: 'Записаться на консультацию' } },
      { type: 'video', content: { title: 'Отзывы клиентов' } },
      { type: 'testimonial', content: { count: 56 } },
      { type: 'download', content: { title: 'Гайд: 10 ошибок стартапов' } },
    ],
  },
  {
    id: 'demo-business-2',
    slug: 'demo-accounting',
    title: 'ProБухгалтерия',
    description: 'Бухгалтерские услуги для ИП и ТОО. Сдача отчетности, консультации.',
    avatar_url: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=200&h=200&fit=crop',
    preview_url: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&h=600&fit=crop',
    gallery_likes: 234,
    view_count: 5600,
    is_premium: true,
    niche: 'business' as Niche,
    gallery_featured_at: new Date().toISOString(),
    isDemo: true,
    tier: 'business',
    blocks: [
      { type: 'profile', content: { name: 'ProБухгалтерия', bio: 'Ваши цифры в надежных руках 📊' } },
      { type: 'pricing', content: { title: 'Тарифы обслуживания' } },
      { type: 'catalog', content: { title: 'Услуги', categories: ['ИП', 'ТОО', 'Отчетность', 'Консультации'] } },
      { type: 'form', content: { title: 'Получить расчет' } },
      { type: 'faq', content: { questions: 10 } },
      { type: 'testimonial', content: { count: 19 } },
      { type: 'messenger', content: { whatsapp: true, telegram: true } },
    ],
  },

  // ========== HEALTH (2 pages) ==========
  {
    id: 'demo-health-1',
    slug: 'demo-psychologist',
    title: 'Ольга | Психолог',
    description: 'Онлайн-консультации. Тревожность, отношения, самооценка. Мягко и бережно.',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&h=200&fit=crop&crop=face',
    preview_url: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=800&h=600&fit=crop',
    gallery_likes: 1234,
    view_count: 19800,
    is_premium: true,
    niche: 'health' as Niche,
    gallery_featured_at: new Date().toISOString(),
    isDemo: true,
    tier: 'business',
    blocks: [
      { type: 'profile', content: { name: 'Ольга Смирнова', title: 'Психолог', bio: 'Помогаю найти опору в себе 🌿' } },
      { type: 'pricing', content: { title: 'Форматы консультаций' } },
      { type: 'booking', content: { title: 'Записаться на сессию' } },
      { type: 'video', content: { title: 'Обо мне' } },
      { type: 'testimonial', content: { count: 78 } },
      { type: 'faq', content: { questions: 6 } },
      { type: 'messenger', content: { telegram: true } },
    ],
  },
  {
    id: 'demo-health-2',
    slug: 'demo-nutrition',
    title: 'Карина | Нутрициолог',
    description: 'Составление рациона. Похудение, набор массы, спортивное питание.',
    avatar_url: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=200&h=200&fit=crop&crop=face',
    preview_url: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800&h=600&fit=crop',
    gallery_likes: 567,
    view_count: 9100,
    is_premium: true,
    niche: 'health' as Niche,
    gallery_featured_at: new Date().toISOString(),
    isDemo: true,
    tier: 'business',
    blocks: [
      { type: 'profile', content: { name: 'Карина Бекова', title: 'Нутрициолог', bio: 'Здоровое питание без голода и стресса 🥗' } },
      { type: 'before-after', content: { title: 'Результаты клиентов' } },
      { type: 'product', content: { title: 'Персональный план питания', price: 45000 } },
      { type: 'booking', content: { title: 'Консультация' } },
      { type: 'download', content: { title: 'Гайд: 7 дней здорового питания' } },
      { type: 'testimonial', content: { count: 43 } },
      { type: 'messenger', content: { whatsapp: true, instagram: true } },
    ],
  },

  // ========== FASHION (2 pages) ==========
  {
    id: 'demo-fashion-1',
    slug: 'demo-stylist',
    title: 'Диана | Стилист',
    description: 'Разбор гардероба, шопинг-сопровождение, капсульный гардероб.',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&h=200&fit=crop&crop=face',
    preview_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop',
    gallery_likes: 789,
    view_count: 12100,
    is_premium: true,
    niche: 'fashion' as Niche,
    gallery_featured_at: new Date().toISOString(),
    isDemo: true,
    tier: 'business',
    blocks: [
      { type: 'profile', content: { name: 'Диана Ким', title: 'Стилист', bio: 'Помогу найти свой стиль ✨' } },
      { type: 'before-after', content: { title: 'Преображения' } },
      { type: 'pricing', content: { title: 'Услуги' } },
      { type: 'booking', content: { title: 'Записаться' } },
      { type: 'carousel', content: { images: 12 } },
      { type: 'testimonial', content: { count: 34 } },
      { type: 'socials', content: { instagram: true, pinterest: true } },
    ],
  },
  {
    id: 'demo-fashion-2',
    slug: 'demo-handmade',
    title: 'SewLove | Авторская одежда',
    description: 'Платья и костюмы ручной работы. Индивидуальный пошив по меркам.',
    avatar_url: 'https://images.unsplash.com/photo-1558171813-4c088753af8f?w=200&h=200&fit=crop',
    preview_url: 'https://images.unsplash.com/photo-1445205170230-053b83016050?w=800&h=600&fit=crop',
    gallery_likes: 456,
    view_count: 7800,
    is_premium: true,
    niche: 'fashion' as Niche,
    gallery_featured_at: new Date().toISOString(),
    isDemo: true,
    tier: 'business',
    blocks: [
      { type: 'profile', content: { name: 'SewLove', bio: 'Одежда, созданная для вас 🧵' } },
      { type: 'catalog', content: { title: 'Коллекции', items: 28 } },
      { type: 'pricing', content: { title: 'Пошив на заказ' } },
      { type: 'form', content: { title: 'Заказать изделие' } },
      { type: 'carousel', content: { images: 16 } },
      { type: 'video', content: { title: 'Процесс создания' } },
      { type: 'messenger', content: { whatsapp: true, instagram: true } },
    ],
  },

  // ========== TRAVEL (2 pages) ==========
  {
    id: 'demo-travel-1',
    slug: 'demo-travel-guide',
    title: 'Нурлан | Гид по Казахстану',
    description: 'Авторские туры по Алматы и области. Чарынский каньон, Кольсайские озера.',
    avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop&crop=face',
    preview_url: 'https://images.unsplash.com/photo-1527631746610-bca00a040d60?w=800&h=600&fit=crop',
    gallery_likes: 934,
    view_count: 15600,
    is_premium: true,
    niche: 'travel' as Niche,
    gallery_featured_at: new Date().toISOString(),
    isDemo: true,
    tier: 'business',
    blocks: [
      { type: 'profile', content: { name: 'Нурлан Сериков', title: 'Гид', bio: 'Покажу красоту Казахстана 🏔️' } },
      { type: 'carousel', content: { images: 20 } },
      { type: 'catalog', content: { title: 'Маршруты', items: 8 } },
      { type: 'pricing', content: { title: 'Стоимость туров' } },
      { type: 'booking', content: { title: 'Забронировать тур' } },
      { type: 'testimonial', content: { count: 67 } },
      { type: 'messenger', content: { whatsapp: true, telegram: true } },
    ],
  },
  {
    id: 'demo-travel-2',
    slug: 'demo-travel-agency',
    title: 'Wanderlust Travel',
    description: 'Туристическое агентство. Туры по СНГ и миру. Визовая поддержка.',
    avatar_url: 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=200&h=200&fit=crop',
    preview_url: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&h=600&fit=crop',
    gallery_likes: 567,
    view_count: 9400,
    is_premium: true,
    niche: 'travel' as Niche,
    gallery_featured_at: new Date().toISOString(),
    isDemo: true,
    tier: 'business',
    blocks: [
      { type: 'profile', content: { name: 'Wanderlust Travel', bio: 'Путешествия мечты под ключ ✈️' } },
      { type: 'catalog', content: { title: 'Горящие туры' } },
      { type: 'pricing', content: { title: 'Направления' } },
      { type: 'countdown', content: { title: 'Скидка на Мальдивы -30%' } },
      { type: 'form', content: { title: 'Подобрать тур' } },
      { type: 'faq', content: { questions: 8 } },
      { type: 'map', content: { address: 'Алматы, пр. Достык 89' } },
    ],
  },

  // ========== REALESTATE (2 pages) ==========
  {
    id: 'demo-realestate-1',
    slug: 'demo-realtor',
    title: 'Асем | Риелтор Алматы',
    description: 'Покупка, продажа, аренда недвижимости. 8 лет на рынке, 300+ сделок.',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&h=200&fit=crop&crop=face',
    preview_url: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop',
    gallery_likes: 345,
    view_count: 6700,
    is_premium: true,
    niche: 'realestate' as Niche,
    gallery_featured_at: new Date().toISOString(),
    isDemo: true,
    tier: 'business',
    blocks: [
      { type: 'profile', content: { name: 'Асем Нурланова', title: 'Риелтор', bio: 'Помогу найти идеальный дом 🏠' } },
      { type: 'catalog', content: { title: 'Объекты в продаже', items: 15 } },
      { type: 'form', content: { title: 'Оставить заявку' } },
      { type: 'testimonial', content: { count: 45 } },
      { type: 'video', content: { title: 'Видео-обзоры квартир' } },
      { type: 'faq', content: { questions: 7 } },
      { type: 'messenger', content: { whatsapp: true, telegram: true } },
    ],
  },
  {
    id: 'demo-realestate-2',
    slug: 'demo-apartment-rent',
    title: 'CityFlat | Аренда квартир',
    description: 'Посуточная аренда квартир в центре Алматы. Уборка, трансфер.',
    avatar_url: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=200&h=200&fit=crop',
    preview_url: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&h=600&fit=crop',
    gallery_likes: 289,
    view_count: 5200,
    is_premium: true,
    niche: 'realestate' as Niche,
    gallery_featured_at: new Date().toISOString(),
    isDemo: true,
    tier: 'business',
    blocks: [
      { type: 'profile', content: { name: 'CityFlat', bio: 'Уютные квартиры для вашего отдыха 🌃' } },
      { type: 'catalog', content: { title: 'Квартиры', items: 12 } },
      { type: 'pricing', content: { title: 'Цены' } },
      { type: 'booking', content: { title: 'Забронировать' } },
      { type: 'carousel', content: { images: 24 } },
      { type: 'testimonial', content: { count: 89 } },
      { type: 'map', content: { address: 'Алматы, центр города' } },
    ],
  },

  // ========== EVENTS (2 pages) ==========
  {
    id: 'demo-events-1',
    slug: 'demo-event-planner',
    title: 'EventPro | Организация мероприятий',
    description: 'Свадьбы, корпоративы, дни рождения. Полный цикл организации.',
    avatar_url: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=200&h=200&fit=crop',
    preview_url: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=800&h=600&fit=crop',
    gallery_likes: 678,
    view_count: 11300,
    is_premium: true,
    niche: 'events' as Niche,
    gallery_featured_at: new Date().toISOString(),
    isDemo: true,
    tier: 'business',
    blocks: [
      { type: 'profile', content: { name: 'EventPro', bio: 'Создаем незабываемые события 🎉' } },
      { type: 'carousel', content: { images: 18 } },
      { type: 'catalog', content: { title: 'Услуги', categories: ['Свадьбы', 'Корпоративы', 'Дни рождения'] } },
      { type: 'pricing', content: { title: 'Пакеты' } },
      { type: 'form', content: { title: 'Обсудить мероприятие' } },
      { type: 'testimonial', content: { count: 56 } },
      { type: 'community', content: { team: 8 } },
    ],
  },
  {
    id: 'demo-events-2',
    slug: 'demo-mc-host',
    title: 'Тимур | Ведущий',
    description: 'Ведущий свадеб и мероприятий. Яркий, душевный, с чувством юмора.',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face',
    preview_url: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=600&fit=crop',
    gallery_likes: 423,
    view_count: 7600,
    is_premium: true,
    niche: 'events' as Niche,
    gallery_featured_at: new Date().toISOString(),
    isDemo: true,
    tier: 'business',
    blocks: [
      { type: 'profile', content: { name: 'Тимур Касымов', title: 'Ведущий', bio: 'Ваш праздник - моя работа и страсть 🎤' } },
      { type: 'video', content: { title: 'Видео с мероприятий' } },
      { type: 'pricing', content: { title: 'Стоимость' } },
      { type: 'booking', content: { title: 'Забронировать дату' } },
      { type: 'carousel', content: { images: 14 } },
      { type: 'testimonial', content: { count: 67 } },
      { type: 'messenger', content: { whatsapp: true, instagram: true } },
    ],
  },

  // ========== SERVICES (2 pages) ==========
  {
    id: 'demo-services-1',
    slug: 'demo-cleaning',
    title: 'CleanHome | Клининг',
    description: 'Уборка квартир и офисов. Генеральная, поддерживающая, после ремонта.',
    avatar_url: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=200&h=200&fit=crop',
    preview_url: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800&h=600&fit=crop',
    gallery_likes: 234,
    view_count: 4500,
    is_premium: true,
    niche: 'services' as Niche,
    gallery_featured_at: new Date().toISOString(),
    isDemo: true,
    tier: 'business',
    blocks: [
      { type: 'profile', content: { name: 'CleanHome', bio: 'Чистота в вашем доме 🧹' } },
      { type: 'pricing', content: { title: 'Услуги и цены' } },
      { type: 'before-after', content: { title: 'До и после' } },
      { type: 'form', content: { title: 'Заказать уборку' } },
      { type: 'testimonial', content: { count: 123 } },
      { type: 'faq', content: { questions: 6 } },
      { type: 'messenger', content: { whatsapp: true } },
    ],
  },
  {
    id: 'demo-services-2',
    slug: 'demo-auto-service',
    title: 'AutoFix | Автосервис',
    description: 'Ремонт и обслуживание авто. Диагностика, ТО, кузовной ремонт.',
    avatar_url: 'https://images.unsplash.com/photo-1487754180451-c456f719a1fc?w=200&h=200&fit=crop',
    preview_url: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800&h=600&fit=crop',
    gallery_likes: 345,
    view_count: 6200,
    is_premium: true,
    niche: 'services' as Niche,
    gallery_featured_at: new Date().toISOString(),
    isDemo: true,
    tier: 'business',
    blocks: [
      { type: 'profile', content: { name: 'AutoFix', bio: 'Ваш надежный автосервис 🚗' } },
      { type: 'catalog', content: { title: 'Услуги', categories: ['Диагностика', 'ТО', 'Ремонт', 'Шиномонтаж'] } },
      { type: 'pricing', content: { title: 'Прайс-лист' } },
      { type: 'booking', content: { title: 'Записаться на ремонт' } },
      { type: 'carousel', content: { images: 10 } },
      { type: 'testimonial', content: { count: 78 } },
      { type: 'map', content: { address: 'Алматы, ул. Райымбека 221' } },
    ],
  },

  // ========== OTHER (2 pages) ==========
  {
    id: 'demo-other-1',
    slug: 'demo-pet-grooming',
    title: 'PetStyle | Груминг',
    description: 'Стрижка и уход за собаками и кошками. Нежно, профессионально.',
    avatar_url: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=200&h=200&fit=crop',
    preview_url: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=800&h=600&fit=crop',
    gallery_likes: 567,
    view_count: 8900,
    is_premium: true,
    niche: 'other' as Niche,
    gallery_featured_at: new Date().toISOString(),
    isDemo: true,
    tier: 'business',
    blocks: [
      { type: 'profile', content: { name: 'PetStyle', bio: 'Красота для ваших питомцев 🐕' } },
      { type: 'carousel', content: { images: 16 } },
      { type: 'pricing', content: { title: 'Услуги и цены' } },
      { type: 'booking', content: { title: 'Записаться' } },
      { type: 'before-after', content: { title: 'До и после' } },
      { type: 'testimonial', content: { count: 89 } },
      { type: 'messenger', content: { whatsapp: true, instagram: true } },
    ],
  },
  {
    id: 'demo-other-2',
    slug: 'demo-astrologer',
    title: 'Айгерим | Астролог',
    description: 'Натальные карты, прогнозы, консультации. Ведическая астрология.',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop&crop=face',
    preview_url: 'https://images.unsplash.com/photo-1532968961962-8a0cb3a2d4f5?w=800&h=600&fit=crop',
    gallery_likes: 678,
    view_count: 10200,
    is_premium: true,
    niche: 'other' as Niche,
    gallery_featured_at: new Date().toISOString(),
    isDemo: true,
    tier: 'business',
    blocks: [
      { type: 'profile', content: { name: 'Айгерим', title: 'Астролог', bio: 'Звезды расскажут о вашей судьбе ✨' } },
      { type: 'pricing', content: { title: 'Услуги' } },
      { type: 'product', content: { title: 'Натальная карта полный разбор', price: 35000 } },
      { type: 'booking', content: { title: 'Записаться на консультацию' } },
      { type: 'testimonial', content: { count: 112 } },
      { type: 'video', content: { title: 'Обо мне и моем подходе' } },
      { type: 'messenger', content: { telegram: true } },
    ],
  },
];

/**
 * Get demo pages count by niche
 */
export function getDemoPagesByNiche(niche: Niche): DemoPage[] {
  return DEMO_PAGES.filter(page => page.niche === niche);
}

/**
 * Get all demo pages
 */
export function getAllDemoPages(): DemoPage[] {
  return DEMO_PAGES;
}

/**
 * Check if a page is a demo page
 */
export function isDemoPage(pageId: string): boolean {
  return pageId.startsWith('demo-');
}
