// This file is automatically generated. Do not edit it directly.
// Redirecting to the main platform client to ensure singleton pattern
import { supabase as platformSupabase } from '../../platform/supabase/client';

export const supabase = platformSupabase;
